import re

bad_words = [re.compile(x, re.I) for x in [
    "texas.hold",
    "online.poker",
    r"^\s*\<h1\>",
    "highprofitclub",
#    "you are invited to visit (the sites about|some helpful info)",
#    "in your free time, check the sites dedicated",
    "3.card.poker",
    "phentermine",
    "hydrocone",
    "hydrocodone",
    "doobu.com",
    "nutzu.com",
    "construction-equipment-resources.com",
    "freemoney.com",
    " cialis ",
    "percocet",
    "pinpain.com",
    "shop263.com",
    "free.roulette",
    "online.casino",
    "highest.payout",
    "internet.casino",
    "online.wines",
    "casino.bonus",
    "kohavi",
    "penis.enlargement",
    ".yoll.net",
    "levitra",
    "vardenafil",
    "sildenafil",
    "ofloxacin",
    "oxybutynin",
    ".nicis-shop.de",
    "lawn-care-system",
    "hair-restoration",
    "excellent(meds|pills).com",
    "generalsteel",
    "general steel",
    "qualityrxpills.com",
    "discount-pills.biz",
    " vicodin ",
    "birthcpills.com",
    "dvd.netleih.de",
    "intimplace.com",
    "quality-generic.com",
    "loan-consolidation",
    "bestcasinos",
    "poker",
    "atlantawebpackages",
    "pacific.poker",
    "credit.report",
    "loan.payment",
    "texas.hold.em",
    "empire.poker",
    "debt.elimination",
    "mortgage",
    "online.poker",
    "pharmacies.online",
    "play.roulette",
    "plavix",
    "diazepan",
    "prilosec",
    "blackjack",
    "holdem",
    "craps.online",
    "slots.online",
    "credit.bureau",
    "keno.jeux",
    "seven.card.stud",
    "baccarat",
    "xyban",
    "cephalexin",
    "spyware.killer",
    "oxycontin",
    "craps.rules",
    "card.stud",
    "www.888",
    "quit.smoking",
    "xanax",
    "flexeril",
    "leather.sofas",
    "bad.credit",
    "personal.loan",
    "credit.card",
    "xenical",
    "diazepam",
    "lipitor",
    "diet.pill",
    "ultracet",
    "naproxen",
    "lamisil",
    "zyban",
    "(free|online|cheap|play|video).(keno|slots|prozac|nexium|ambien|zyrtec|skelaxin|paxil|craps|bingo|didrex|renova|darvon|bextra|fosamax|zoloft|valtrex|lorcet|celebrex|tenuate|valium|casino|alprazolam|diovan|coreg|vioxx|allegra)",
    "(clonazepam|acyclovir|zyrtec|ambien|keno|valium|bextra|craps|jack|meridia|ativan).(online|strategy|odds)",
    "glucophage",
    "fetal.monitor",
    "keno.game",
    "provigil",
    "payday.(loan|cash|advance)",
    "carisoprodol",
    "dish.network",
    "fioricet",
    "weight.loss",
    "zyprexa",
    "wrinkle.cream",
    "black jack",
    "def.rimjob",
    "testosterone",
    "arthritis",
    "vigrx",
    "vicodin",
    "adderall",
    "diabetes",
    "lortab",
    "discount.airfare",
    "hydrochloride",
    "steroid",
    "atenolol",
    "drug interaction",
    "bontril",
    "diet loss",
    "10mg",
    "doxycycline",
    "accutane",
    "online.pharmacy",
    "business.grants",
    
    
    ]]

def is_spam(*words):
    for matcher in bad_words:
        for word in words:
            if matcher.search(word):
                return 1
    return 0
